changelog:
  exclude:
    labels:
      - skip-changelog
  categories:
    - title: Breaking changes
      labels:
        - breaking
    - title: Features
      labels:
        - feature
        - enhancement
    - title: Fixes
      labels:
        - bug
    - title: Performance
      labels:
        - performance
    - title: Documentation
      labels:
        - documentation
    - title: Packaging and CI
      labels:
        - packaging
        - ci
    - title: Dependencies
      labels:
        - dependencies
    - title: Other changes
      labels:
        - "*"
